

services:


stages:
  - build
  - deploy

# Stage: build
##############################################################################

build:docker:
  stage: build
  image: docker
  script:
    - docker build --tag ${CI_REGISTRY_IMAGE} .
  tags:
    - docker

build:precommit:
  stage: build
  image: python:3.9
  before_script:
  - pip3 install -r requirements-dev.txt
  script:
  - pre-commit run --all-files
  tags:
    - docker

build:test:
  stage: build
  image: python:3.9
  services:
  - rabbitmq:latest
  before_script:
  - pip3 install -r requirements-dev.txt
  script:
  - pytest
  tags:
    - docker

build:dist:
  stage: build
  image: python:3.9
  script:
    - python3 setup.py sdist
  artifacts:
    paths:
      - dist/
  tags:
    - docker

# Stage: deploy
##############################################################################

deploy:docker:
  stage: deploy
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker push ${CI_REGISTRY_IMAGE}
  tags:
    - shell
    - linux
  only:
    - ci-docker
